### ISSUE TITLE
Remove senseBoxMCU-Lib library

### ISSUE THREAD

**Issue by mpfeil** [sensebox/senseBoxMCU-core#9]
Completly remove [senseBoxMCU Lib](https://github.com/sensebox/senseBoxMCU-core/tree/master/arduino/samd/libraries/SenseBox-MCU) from this repository becuase it is only needed by `ardublockly` and therefore can be included in `sensebox-sketches`

**Comment by mariopesch** [comment]
I've just saw that the projects in the :edu book use some functions of the senseBox MCU Lib. Therefore it need to be integrated in the core support package.
